### PR TITLE
GeometryGroups

### PR DESCRIPTION
**Pull request by chmerdon**
new type CellGeometryGroups that collects all cells with same CellGeometry as ordered in UniqueCellGeometries

### CODE REVIEW

**Comment by chmerdon** [comment]
Main idea: GeometryGroups can be used to split assembly loops into loops with a homogeneous geometry, which I expect might help resolve some efficiency issues in the assembly loops of GradientRobustMultiPhysics.

For future parallel assembly infrastructure I suggest to have another type that also should make sure that every group has a homogeneous Geometry, possible by building adjacencies like CellAssemblyGroups and CellAssemblyGroupGeometries.

Or is it better to have this at once, and have the GeometryGroups/UniqueCellGeometries as the (serial assembly) default for CellAssemblyGroups/CellAssemblyGroupGeometries? One could also add an Integer parameter to the type to encode for which number of parallel.

**Comment by j-fu** [comment]
> Or is it better to have this at once, and have the GeometryGroups/UniqueCellGeometries as the (serial assembly) default for CellAssemblyGroups/CellAssemblyGroupGeometries? 

IMHO this would be the best variant. I don't think that we need two infrasstructures here. There will be anyway something on top of the CellAssemblyGroups.

> One could also add an Integer parameter to the type to encode for which number of parallel processes the groups are intended. 

If possible I would delay this decision - it is not yet clear how things will play out, and I feel deciding now would be premature.

**Comment by chmerdon** [comment]
Agreed, then I rewrite the pull request for CellAssemblyGroups/CellAssemblyGroupsGeometry (+ same for Face, BFace, Edge, BEdge) with the suggested default instantiations.

**Comment by chmerdon** [comment]
I renamed them to CellAssemblyGroups etc. I did not add yet the AssemblyGroupsGeometry, since that can be derived at runtime by looking at the geometry of the first cell in each group (or by looking into UniqueCellgeometries). We can decide to add that later when we have a clearer concept for the parallelization.

**Comment by j-fu** [comment]
Current VoronoiFVM works with this PR.

**Pull request merged**
