### PR TITLE
Added function for writing grid structure to vtk_write

### PR DESCRIPTION
**Pull request by mattlie82**
The writing of the VTK files uses the WriteVTK.jl package.
Hence, it was added as dependency. In addition to the grid structure,
point, cell, or field data can be written to the file.

### CODE REVIEW

**Comment by j-fu** [comment]
Looks quite good!
Could you please add:
- unit test in runtests.jl
- compat entry for WriteVTK
- docstring  including description what kwargs can do

**Comment by chmerdon** [comment]
Tested it with some kwargs and it works fine for me.

**Comment by chmerdon** [comment]
I added the compat info and a short example in runtest.jl (it is not a real test though since it is hard to verify the output). I removed write_regions, since one can use the kwargs for that (regions = grid[CellRegions]). btw: the WriteVTK magic also accepts vector data without problems, which is really nice. Something else to do?

**Comment by chmerdon** [comment]
Aha, WriteVTK needs julia1.6, are we okay with adopting this requirement for ExtendableGrids?

**Comment by chmerdon** [comment]
what about computing the sha256 hash and comparing with a hard-coded correct one? (inspired by last answer in https://stackoverflow.com/questions/49383205/compare-two-buffers-for-equality)

**Comment by j-fu** [comment]
Good idea. There are  hash()  and SHA.sha256 etc in Julia. I think hash() is sufficient.

**Comment by mattlie82** [comment]
The reason why I didn't revise my last pull request was that I got an error when writing more than one vector field:
Could you confirm that the following does not work:

```
    X = collect(-1:1.0:1)
    Y = collect(-1:1.0:1)
    Z = collect(0:0.5:1)
    g = simplexgrid(X,Y,Z)

    nx = num_nodes(g)
    nc = num_cells(g)

    point_data    = map((x,y,z) -> (sinpi(2*x)*sinpi(2*y)*z), g)
    
    cell_data  = rand(Float64, nc)
    field_data = [1.0, 2, 3, 4, 5, 6]
    
    rnd_vector_data = rand(Float64, (3,nx))
    rnd_vector_data2 = rand(Float64, (3,nx))

    writeVTK(filename, g, true; point_data = point_data, 
                              cell_data = cell_data, 
                              field_data = field_data,
                              rnd_vector_data = @views (rnd_vector_data[1,:], rnd_vector_data[2,:], rnd_vector_data[3,:]),
                             rnd_vector_data2 = @views (rnd_vector_data2[1,:], rnd_vector_data2[2,:], rnd_vector_data2[3,:])
)
```

**Comment by chmerdon** [comment]
this works for me:

writeVTK("testfile_writevtk.vtu", g; cellregions = grid[CellRegions], point_data = point_data, 
                              cell_data = cell_data, 
                              field_data = field_data,
                              rnd_vector_data = rnd_vector_data,
                             rnd_vector_data2 = rnd_vector_data2)

**Comment by chmerdon** [comment]
ok, now everything seems to work besides the julia1.3 tests... for which we need to update the workflow file after merging, I guess. Is it ok to merge now?

**Comment by j-fu** [comment]
yes, it should be merged...

**Pull request merged**
