### PR TITLE
unionize abstract types

### PR DESCRIPTION
**Pull request by j-fu**
Use "ElementGeomtries" -- union of Geometry leaf types -- as eltype for CellGeometries,BFaceGeometries

Similar with CoordinateSystems.

This relies on the built-in union split of Julia which seems to have
no union size constraint anymore. This may remove some allocations...

See https://discourse.julialang.org/t/avoiding-vectors-of-abstract-types/61883/11

### CODE REVIEW

**Comment by j-fu** [comment]
As a further remark:
Julia turns the dynamic dispatch into a "union split" which essentially seems to perform like a realization of the manual dispatch, i.e. the if-then-else structure testing possible types. The prerequisite is that the element type of the Array is a union of a finite number of possible types. It seems that the idea that this works has been lost a bit....

**Comment by chmerdon** [comment]
ok, we should try this

unfortunately, so far I don't see an improvement e.g. in the calculation of CellVolumes, but this may have other reasons

Also, I get an error when using UniqueBFaceGeometries, its instantiation needs to cast it into an Array{ElementGeometries,1} as you did with UniqueCellGeometries etc. (also the other UniqueGeometries).

**Comment by chmerdon** [comment]
I comited a fix for what I mentioned above.

I also improved the allocations in the instantiate of CellVolumes (or other XYZVolumes) by removing the closures. There are still allocations but I observed that if I call these functions with a fixed CoordinateSystem then all allocations vanish, so only the dispatch on the CoordinateSystem seems to cause problems now.

**Comment by chmerdon** [comment]
I think now it seems to work with all dispatches, I had to add some type annotations. You can test e.g. with

xgrid = uniform_refine(grid_unitsquare(Triangle2D),5)
@time xCellVolumes = xgrid[CellVolumes]

**Comment by j-fu** [comment]
So it is ready to merge  ?
BTW, see https://github.com/JuliaLang/julia/pull/44131

**Comment by j-fu** [comment]
Not completely sure why they are needed (I need them as well from time to time).

The idea of the types as keys allows to make the getindex methods type stable, they
need to be specialized  if necessary. 

Type stability of methods should be  sufficient, no need to require
a function  to be type stable...

In 
https://discourse.julialang.org/t/confusion-about-type-stability-functions-or-methods/62277
Fredrik Ekre (who should know) clearly say: methods must be type stable.


This PR has  a new method for `getindex(ExtendableGrid,CoordinateSystem)` though...

**Comment by j-fu** [comment]
Re #2c66984 : There were still missing type stable wrappers for getindex for Integer arrays.
CoordinateSystem should work though without allocations.

**Comment by chmerdon** [comment]
No further issues on my end, I think it's ready to merge now.

**Pull request merged**
